services:
  dataoncustomers:
    image: dataoncustomers
    container_name: dataon-customers
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ACCESS_TOKEN: ${ACCESS_TOKEN}
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
